name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - service: backend
            context: .
            file: Dockerfile.backend
          - service: dashboard
            context: dashboard
            file: dashboard/Dockerfile
            build_args: |
              NEXT_PUBLIC_API_BASE=
              BACKEND_INTERNAL_URL=http://backend:8000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare image prefix
        id: meta
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "image_prefix=${OWNER_LC}/pricesentry" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_prefix }}-${{ matrix.service }}:latest
            ${{ env.REGISTRY }}/${{ steps.meta.outputs.image_prefix }}-${{ matrix.service }}:${{ github.sha }}
          build-args: ${{ matrix.build_args || '' }}
